model:
  base_learning_rate: 4.5e-06
  target: ldm.models.duration.DurPredModel
  params:
    monitor: val/dur_loss    # <--- main.py 会自动读取这个指标来配置 Checkpoint
    ddconfig:
      hidden_size: 256
      dur_predictor_kernel: 3
      dur_predictor_layers: 2
      predictor_dropout: 0.5
      dropout: 0.0
      enc_layers: 4
      enc_ffn_kernel_size: 9
      enc_prenet: true
      enc_pre_ln: true
      num_heads: 2

lightning:
  trainer:
    sync_batchnorm: false
    strategy: ddp               # 多卡分布式训练策略

data:
  target: main.LatentDataModuleFromConfig  # 使用你最新重构的类名
  params:
    batch_size: 64
    num_workers: 4
    data_dir: ./data/final      # 新的精简目录参数
    latent_channels: 128
    latent_crop_len: 500
    train:
      target: ldm.dataset.joinaudiodataset_dur.DurTrainDataset
      params:
        dataset_cfg:
          max_ph_len: 150
          latent_downsample_factor: 1
    validation:
      target: ldm.dataset.joinaudiodataset_dur.DurValidationDataset
      params:
        dataset_cfg:
          max_ph_len: 150
          latent_downsample_factor: 1