model:
  base_learning_rate: 1.0e-04  # 因为去掉了厚重的VAE，纯回归任务学习率可以从 4.5e-6 提高到 1e-4
  target: ldm.models.duration.DurPredModel  # ⚠️ 确保改成你实际存放我们重写的那个 Duration 类的路径
  params:
    monitor: val/dur_loss      # 监控指标
    ddconfig:
      # 保留所有与 Transformer (音素编码) 和 Duration 相关的参数
      hidden_size: 256
      dur_predictor_kernel: 3
      dur_predictor_layers: 2
      predictor_dropout: 0.5
      enc_layers: 4
      enc_ffn_kernel_size: 9
      enc_prenet: true
      enc_pre_ln: true
      num_heads: 2

lightning:
  callbacks:
    # 替换原来的 AudioLogger 为模型权重自动保存 (ModelCheckpoint)
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        monitor: val/dur_loss   # 监视验证集的时长误差
        mode: min               # 误差越小越好
        save_top_k: 3           # 自动保留表现最好的 3 个 epoch 的权重
        filename: "dur-model-{epoch:02d}-{val_dur_loss:.4f}" # 保存的文件名格式
  trainer:
    sync_batchnorm: false
    strategy: ddp               # 多卡分布式训练策略
    # max_epochs: 200           # 你可以在这里指定最大训练轮数

data:
  # ⚠️ 注意这里：必须是 DataModule，而不是你的网络模型
  target: main.SpectrogramDataModuleFromConfig 
  params:
    batch_size: 64              # 单卡 batch_size (纯文本训练不占显存，可调大)
    num_workers: 4
    spec_dir_path: ./data/final # 直接指向包含 tsv 的文件夹
    train:
      target: ldm.data.duration_dataset.DurTrainDataset
      params:
        dur_dataset_cfg:
          max_ph_len: 150
          latent_downsample_factor: 1 # 根据你预训练 VAE 的真实降采样率填写
    validation:
      target: ldm.data.duration_dataset.DurValidationDataset
      params:
        dur_dataset_cfg:
          max_ph_len: 150
          latent_downsample_factor: 1